In [13]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import matplotlib.pyplot as plt
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

In [14]:
filename_queue = tf.train.string_input_producer(
['data-01-test-score.csv'],shuffle=False,name='filename_queue')

In [15]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

default value, in cast of empty columns. Also specifies the type of the
decoded result.

In [4]:
record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value,record_defaults=record_defaults)

collect batches of csv in

In [16]:
train_x_batch, train_y_batch =  tf.train.batch([xy[0:-1],xy[-1:]],batch_size=10)

placeholders for a tensor that will be always fed

In [6]:
X = tf.placeholder(tf.float32,shape=[None,3])
Y = tf.placeholder(tf.float32,shape=[None,1])

W = tf.Variable(tf.random_normal([3,1]),name='weight')
b = tf.Variable(tf.random_normal([1]),name='bias')

hypothesis

In [7]:
hypothesis = tf.matmul(X,W)+b

simplified cost/loss function

In [8]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

minimize

In [9]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

launch the graph in a session.

In [10]:
sess = tf.Session()

#Initializes global variables in the graph

In [11]:
sess.run(tf.global_variables_initializer())

start populating the filenmae queue.

In [12]:
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch,y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
    [cost,hypothesis,train],feed_dict = {X:x_batch,Y:y_batch})
    if step % 10 == 0:
        print(step,"Cost : ",cost_val, "\nPredictoin:\n",hy_val)
        
coord.request_stop()
coord.join(threads)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
0 Cost :  862.8553 
Predictoin:
 [[122.69893]
 [151.19644]
 [147.00003]
 [160.77475]
 [115.67936]
 [ 86.77743]
 [120.31759]
 [ 89.04543]
 [143.00249]
 [134.29672]]
10 Cost :  7.023594 
Predictoin:
 [[152.0522  ]
 [186.47484 ]
 [181.76097 ]
 [198.63487 ]
 [142.58218 ]
 [106.615974]
 [148.66187 ]
 [110.06469 ]
 [175.97578 ]
 [164.84416 ]]
20 Cost :  7.435665 
Predictoin:
 [[152.25288 ]
 [186.70894 ]
 [181.99516 ]
 [198.89159 ]
 [142.75754 ]
 [106.74701 ]
 [148.8585  ]
 [110.216965]
 [176.19495 ]
 [165.05022 ]]
30 Cost :  7.4229827 
Predictoin:
 [[152.25685]
 [186.70654]
 [181.99635]
 [198.89456]
 [142.75258]
 [106.74506]
 [148.86522]
 [110.2284 ]
 [176.1931 ]
 [165.05153]]
40 Cost :  7.407206 
Predictoin:
 [[152.25949]
 [186.70256]
 [181.99597]
 [198.89581]
 [142.74638]
 [106.74223]
 [148.87062]
 [110.23888]
 [176.18973]
 [165.05145]]
50 Cost :  7.3914795 
Predictoin:
 [[152.2621  ]
 [186.69858 ]
 [181.995

460 Cost :  6.8116593 
Predictoin:
 [[152.36504 ]
 [186.54283 ]
 [181.98096 ]
 [198.94484 ]
 [142.49925 ]
 [106.627304]
 [149.08496 ]
 [110.65462 ]
 [176.05382 ]
 [165.04443 ]]
470 Cost :  6.7989793 
Predictoin:
 [[152.36743]
 [186.5392 ]
 [181.98062]
 [198.94595]
 [142.49365]
 [106.62467]
 [149.08978]
 [110.66397]
 [176.0507 ]
 [165.04419]]
480 Cost :  6.786358 
Predictoin:
 [[152.36983]
 [186.5356 ]
 [181.98027]
 [198.94704]
 [142.48808]
 [106.62206]
 [149.09459]
 [110.67332]
 [176.04759]
 [165.04396]]
490 Cost :  6.773834 
Predictoin:
 [[152.37224]
 [186.532  ]
 [181.97998]
 [198.94815]
 [142.48253]
 [106.61943]
 [149.0994 ]
 [110.68262]
 [176.04451]
 [165.04372]]
500 Cost :  6.761345 
Predictoin:
 [[152.37463]
 [186.5284 ]
 [181.97964]
 [198.94925]
 [142.47699]
 [106.61682]
 [149.10419]
 [110.69191]
 [176.04141]
 [165.04346]]
510 Cost :  6.7489367 
Predictoin:
 [[152.37703]
 [186.52483]
 [181.97932]
 [198.95033]
 [142.47145]
 [106.61421]
 [149.10896]
 [110.70117]
 [176.03835]
 [165

1110 Cost :  6.109725 
Predictoin:
 [[152.51195 ]
 [186.32428 ]
 [181.96222 ]
 [199.011   ]
 [142.16275 ]
 [106.46639 ]
 [149.374   ]
 [111.215485]
 [175.86359 ]
 [165.02414 ]]
1120 Cost :  6.1006904 
Predictoin:
 [[152.51407 ]
 [186.3212  ]
 [181.96198 ]
 [199.01195 ]
 [142.15799 ]
 [106.464066]
 [149.37808 ]
 [111.2234  ]
 [175.86087 ]
 [165.02379 ]]
1130 Cost :  6.091685 
Predictoin:
 [[152.51617 ]
 [186.3181  ]
 [181.96172 ]
 [199.0129  ]
 [142.15323 ]
 [106.461754]
 [149.38216 ]
 [111.2313  ]
 [175.85814 ]
 [165.02342 ]]
1140 Cost :  6.0826855 
Predictoin:
 [[152.51828]
 [186.31497]
 [181.96146]
 [199.01381]
 [142.14847]
 [106.45944]
 [149.3862 ]
 [111.23918]
 [175.8554 ]
 [165.02303]]
1150 Cost :  6.073785 
Predictoin:
 [[152.52037]
 [186.3119 ]
 [181.96123]
 [199.01474]
 [142.14372]
 [106.45714]
 [149.39024]
 [111.24703]
 [175.85266]
 [165.02264]]
1160 Cost :  6.064883 
Predictoin:
 [[152.52246]
 [186.3088 ]
 [181.96097]
 [199.01566]
 [142.13898]
 [106.45483]
 [149.39429]
 [111.

1620 Cost :  5.7028356 
Predictoin:
 [[152.61427 ]
 [186.17464 ]
 [181.9506  ]
 [199.05574 ]
 [141.93335 ]
 [106.353714]
 [149.5692  ]
 [111.5944  ]
 [175.73048 ]
 [165.0032  ]]
1630 Cost :  5.695866 
Predictoin:
 [[152.61617]
 [186.17188]
 [181.9504 ]
 [199.05655]
 [141.92914]
 [106.35161]
 [149.57278]
 [111.60135]
 [175.72801]
 [165.00276]]
1640 Cost :  5.6889563 
Predictoin:
 [[152.61806]
 [186.16911]
 [181.95018]
 [199.05737]
 [141.92491]
 [106.34952]
 [149.57634]
 [111.60827]
 [175.72554]
 [165.0023 ]]
1650 Cost :  5.682106 
Predictoin:
 [[152.61996]
 [186.16638]
 [181.95   ]
 [199.0582 ]
 [141.92072]
 [106.34743]
 [149.5799 ]
 [111.61517]
 [175.72308]
 [165.00188]]
1660 Cost :  5.6752224 
Predictoin:
 [[152.62181 ]
 [186.16362 ]
 [181.94978 ]
 [199.05898 ]
 [141.91652 ]
 [106.345345]
 [149.58344 ]
 [111.62207 ]
 [175.7206  ]
 [165.00142 ]]
1670 Cost :  5.6684504 
Predictoin:
 [[152.62372 ]
 [186.16089 ]
 [181.94958 ]
 [199.05981 ]
 [141.91234 ]
 [106.34327 ]
 [149.58698 ]
 [111.6