In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import matplotlib.pyplot as plt
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

#placeholders for a tensor that will be always fed.

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

In [4]:
Y = tf.placeholder(tf.float32)

In [18]:
w1 = tf.Variable(tf.random_normal([1]),name='weight1')
w2 = tf.Variable(tf.random_normal([1]),name='weight2')
w3 = tf.Variable(tf.random_normal([1]),name='weight3')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [19]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

#COST/LOSS FUNCTOIN


In [20]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#minimize. Need a very small learning rate for this date set

In [21]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

#launch the graph in a session.

In [22]:
sess = tf.Session()

#Initializes global variables in the graph.

In [27]:
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis, train],
                                   feed_dict={x1: x1_data,x2:x2_data,x3:x3_data,Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ",cost_val, "\nPrediction:\n",hy_val)

0 Cost:  28586.438 
Prediction:
 [0.37969792 4.9524384  2.5552292  3.5776558  4.1110954 ]
10 Cost:  1.0429591 
Prediction:
 [149.94585 184.71709 179.68184 196.46358 141.226  ]
20 Cost:  0.7804189 
Prediction:
 [150.39984 185.26004 180.21826 197.04721 141.6399 ]
30 Cost:  0.7795962 
Prediction:
 [150.40263 185.26073 180.22037 197.049   141.64018]
40 Cost:  0.7787621 
Prediction:
 [150.40408 185.25978 180.22086 197.04901 141.6392 ]
50 Cost:  0.7779326 
Prediction:
 [150.40553 185.25883 180.22133 197.04904 141.63824]
60 Cost:  0.7771162 
Prediction:
 [150.40695 185.25787 180.2218  197.04906 141.63728]
70 Cost:  0.77630395 
Prediction:
 [150.40839 185.25694 180.2223  197.04909 141.63632]
80 Cost:  0.7754924 
Prediction:
 [150.4098  185.256   180.22278 197.0491  141.63536]
90 Cost:  0.774681 
Prediction:
 [150.41122 185.25507 180.22327 197.04912 141.63443]
100 Cost:  0.7738662 
Prediction:
 [150.41264 185.25412 180.22374 197.04912 141.63347]
110 Cost:  0.7730581 
Prediction:
 [150.41406 185

940 Cost:  0.71588504 
Prediction:
 [150.5203  185.1831  180.26024 197.04794 141.56358]
950 Cost:  0.7152971 
Prediction:
 [150.52145 185.18236 180.26065 197.04791 141.56288]
960 Cost:  0.71471107 
Prediction:
 [150.52261 185.1816  180.26103 197.04788 141.56215]
970 Cost:  0.7141278 
Prediction:
 [150.52376 185.18083 180.26143 197.04784 141.56143]
980 Cost:  0.7135449 
Prediction:
 [150.5249  185.18008 180.26181 197.04779 141.56071]
990 Cost:  0.71296215 
Prediction:
 [150.52606 185.17935 180.26222 197.04776 141.56001]
1000 Cost:  0.7123803 
Prediction:
 [150.5272  185.1786  180.26262 197.04771 141.55931]
1010 Cost:  0.7118184 
Prediction:
 [150.52832 185.17786 180.263   197.04767 141.5586 ]
1020 Cost:  0.71123576 
Prediction:
 [150.52946 185.1771  180.26338 197.04762 141.55789]
1030 Cost:  0.7106654 
Prediction:
 [150.5306  185.17636 180.26376 197.04758 141.55719]
1040 Cost:  0.7100965 
Prediction:
 [150.53172 185.17561 180.26416 197.04753 141.55649]
1050 Cost:  0.7095375 
Prediction:

1890 Cost:  0.6679622 
Prediction:
 [150.61865 185.11877 180.2943  197.04207 141.50496]
1900 Cost:  0.6675228 
Prediction:
 [150.61958 185.11816 180.2946  197.04198 141.50443]
1910 Cost:  0.6671084 
Prediction:
 [150.62048 185.11757 180.29494 197.0419  141.5039 ]
1920 Cost:  0.66666675 
Prediction:
 [150.62141 185.11697 180.29526 197.04181 141.5034 ]
1930 Cost:  0.66623646 
Prediction:
 [150.62233 185.11636 180.29558 197.04172 141.50288]
1940 Cost:  0.6658138 
Prediction:
 [150.62325 185.11577 180.2959  197.04164 141.50237]
1950 Cost:  0.66538614 
Prediction:
 [150.62418 185.11519 180.29623 197.04158 141.50188]
1960 Cost:  0.6649515 
Prediction:
 [150.62509 185.11461 180.29657 197.04147 141.50137]
1970 Cost:  0.66453546 
Prediction:
 [150.62599 185.11401 180.29686 197.0414  141.50085]
1980 Cost:  0.6641072 
Prediction:
 [150.62689 185.1134  180.29718 197.04129 141.50035]
1990 Cost:  0.66369444 
Prediction:
 [150.62779 185.11284 180.2975  197.04121 141.49985]
2000 Cost:  0.66328084 
Pre