In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import matplotlib.pyplot as plt
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

#placeholders for a tensor that will be always fed.

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

In [4]:
Y = tf.placeholder(tf.float32)

In [5]:
w1 = tf.Variable(tf.random_normal([1]),name='weight1')
w2 = tf.Variable(tf.random_normal([1]),name='weight2')
w3 = tf.Variable(tf.random_normal([1]),name='weight3')
b = tf.Variable(tf.random_normal([1]),name='bias')

In [6]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

#COST/LOSS FUNCTOIN


In [7]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

#minimize. Need a very small learning rate for this date set

In [8]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

#launch the graph in a session.

In [9]:
sess = tf.Session()

#Initializes global variables in the graph.

In [10]:
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypothesis, train],
                                   feed_dict={x1: x1_data,x2:x2_data,x3:x3_data,Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ",cost_val, "\nPrediction:\n",hy_val)

0 Cost:  28.479574 
Prediction:
 [144.17336 183.50774 175.95833 188.55585 144.67659]
10 Cost:  13.784167 
Prediction:
 [147.57011 187.56532 179.96933 192.92288 147.76598]
20 Cost:  13.71831 
Prediction:
 [147.59357 187.5685  179.98541 192.93954 147.76291]
30 Cost:  13.652928 
Prediction:
 [147.60678 187.55946 179.98941 192.94304 147.7505 ]
40 Cost:  13.5878725 
Prediction:
 [147.61993 187.55038 179.99338 192.94649 147.73811]
50 Cost:  13.523209 
Prediction:
 [147.63301 187.54135 179.9973  192.94994 147.72574]
60 Cost:  13.458887 
Prediction:
 [147.64609 187.53235 180.00124 192.95338 147.71342]
70 Cost:  13.394888 
Prediction:
 [147.65912 187.52335 180.00516 192.9568  147.70113]
80 Cost:  13.331215 
Prediction:
 [147.67212 187.51437 180.00905 192.96022 147.68886]
90 Cost:  13.267926 
Prediction:
 [147.68507 187.50545 180.01295 192.96362 147.67662]
100 Cost:  13.204915 
Prediction:
 [147.698   187.49649 180.01682 192.96701 147.66441]
110 Cost:  13.142346 
Prediction:
 [147.71088 187.4876

1210 Cost:  7.948115 
Prediction:
 [148.93135 186.64447 180.38634 193.29909 146.49171]
1220 Cost:  7.913526 
Prediction:
 [148.94083 186.63792 180.38918 193.30173 146.48265]
1230 Cost:  7.879107 
Prediction:
 [148.95027 186.6314  180.392   193.30434 146.47359]
1240 Cost:  7.844825 
Prediction:
 [148.95967 186.62485 180.39479 193.30692 146.46451]
1250 Cost:  7.8107557 
Prediction:
 [148.9691  186.61836 180.39761 193.30954 146.45552]
1260 Cost:  7.7768493 
Prediction:
 [148.97847 186.6119  180.40042 193.31215 146.44652]
1270 Cost:  7.7431655 
Prediction:
 [148.9878  186.60542 180.40318 193.31473 146.43755]
1280 Cost:  7.709588 
Prediction:
 [148.99713 186.59897 180.40596 193.31734 146.4286 ]
1290 Cost:  7.6763124 
Prediction:
 [149.0064  186.59254 180.40874 193.3199  146.4197 ]
1300 Cost:  7.6431 
Prediction:
 [149.01569 186.58612 180.41151 193.32248 146.4108 ]
1310 Cost:  7.610083 
Prediction:
 [149.02492 186.57971 180.41425 193.32503 146.4019 ]
1320 Cost:  7.5772705 
Prediction:
 [149.